package lojaEsportiva.gui;

import lojaEsportiva.dados.*;
import lojaEsportiva.negocio.*;
import lojaEsportiva.fachada.Fachada;

public class FormPrincipal extends javax.swing.JFrame {
    	//public static Fachada fachada = new Fachada(new CadastroVendas(new RepositorioVendasArray()), new Cadastroprodutos(new RepositorioProdutoArray()), new CadastroFornecedor(new RepositorioArrayFornecedor()), new CadastroFuncionarios(new RepositorioFuncionariosArray()), new CadastroCliente(new RepositorioClienteArray()));
        public static Fachada fachada = new Fachada(new CadastroVendas(new RepositorioVendasLista()), new Cadastroprodutos(new RepositorioProdutosLista()), new CadastroFornecedor(new RepositorioListaFornecedor()), new CadastroFuncionarios(new RepositorioFuncionariosLista()), new CadastroCliente(new RepositorioListaCliente()));
    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnProduto = new javax.swing.JMenu();
        mnCadastrarProduto = new javax.swing.JMenuItem();
        mnConsultarProduto = new javax.swing.JMenuItem();
        mnAlterarProduto = new javax.swing.JMenuItem();
        mnRemoverProduto = new javax.swing.JMenuItem();
        mnCliente = new javax.swing.JMenu();
        mnCadastrarCliente = new javax.swing.JMenuItem();
        mnConsultarCliente = new javax.swing.JMenuItem();
        mnAlterarCliente = new javax.swing.JMenuItem();
        mnRemoverCliente = new javax.swing.JMenuItem();
        mnFuncionario = new javax.swing.JMenu();
        mnCadastrarFuncionario = new javax.swing.JMenuItem();
        mnConsultarFuncionario = new javax.swing.JMenuItem();
        mnAlterarFuncionario = new javax.swing.JMenuItem();
        mnRemoverFuncionario = new javax.swing.JMenuItem();
        mnFornecedor = new javax.swing.JMenu();
        mnCadastrarFornecedor = new javax.swing.JMenuItem();
        mnConsultarFornecedor = new javax.swing.JMenuItem();
        mnAlterarFornecedor = new javax.swing.JMenuItem();
        mnRemoverFornecedor = new javax.swing.JMenuItem();
        mnVenda = new javax.swing.JMenu();
        mnCadastrarVenda = new javax.swing.JMenuItem();
        mnConsultarVenda = new javax.swing.JMenuItem();
        mnAlterarVenda = new javax.swing.JMenuItem();
        mnRemoverVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja Esportiva");
        setName("Loja Esportiva"); // NOI18N
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnProduto.setText("Produto");

        mnCadastrarProduto.setText("Cadastrar");
        mnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarProdutoActionPerformed(evt);
            }
        });
        mnProduto.add(mnCadastrarProduto);

        mnConsultarProduto.setText("Consultar");
        mnConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultarProdutoActionPerformed(evt);
            }
        });
        mnProduto.add(mnConsultarProduto);

        mnAlterarProduto.setText("Alterar");
        mnAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlterarProdutoActionPerformed(evt);
            }
        });
        mnProduto.add(mnAlterarProduto);

        mnRemoverProduto.setText("Remover");
        mnRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRemoverProdutoActionPerformed(evt);
            }
        });
        mnProduto.add(mnRemoverProduto);

        jMenuBar1.add(mnProduto);

        mnCliente.setText("Cliente");

        mnCadastrarCliente.setText("Cadastrar");
        mnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarClienteActionPerformed(evt);
            }
        });
        mnCliente.add(mnCadastrarCliente);

        mnConsultarCliente.setText("Consultar");
        mnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultarClienteActionPerformed(evt);
            }
        });
        mnCliente.add(mnConsultarCliente);

        mnAlterarCliente.setText("Alterar");
        mnAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlterarClienteActionPerformed(evt);
            }
        });
        mnCliente.add(mnAlterarCliente);

        mnRemoverCliente.setText("Remover");
        mnRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRemoverClienteActionPerformed(evt);
            }
        });
        mnCliente.add(mnRemoverCliente);

        jMenuBar1.add(mnCliente);

        mnFuncionario.setText("Funcionário");

        mnCadastrarFuncionario.setText("Cadastrar");
        mnCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarFuncionarioActionPerformed(evt);
            }
        });
        mnFuncionario.add(mnCadastrarFuncionario);

        mnConsultarFuncionario.setText("Consultar");
        mnConsultarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultarFuncionarioActionPerformed(evt);
            }
        });
        mnFuncionario.add(mnConsultarFuncionario);

        mnAlterarFuncionario.setText("Alterar");
        mnAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlterarFuncionarioActionPerformed(evt);
            }
        });
        mnFuncionario.add(mnAlterarFuncionario);

        mnRemoverFuncionario.setText("Remover");
        mnRemoverFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRemoverFuncionarioActionPerformed(evt);
            }
        });
        mnFuncionario.add(mnRemoverFuncionario);

        jMenuBar1.add(mnFuncionario);

        mnFornecedor.setText("Fornecedor");

        mnCadastrarFornecedor.setText("Cadastrar");
        mnCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarFornecedorActionPerformed(evt);
            }
        });
        mnFornecedor.add(mnCadastrarFornecedor);

        mnConsultarFornecedor.setText("Consultar");
        mnConsultarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultarFornecedorActionPerformed(evt);
            }
        });
        mnFornecedor.add(mnConsultarFornecedor);

        mnAlterarFornecedor.setText("Alterar");
        mnAlterarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlterarFornecedorActionPerformed(evt);
            }
        });
        mnFornecedor.add(mnAlterarFornecedor);

        mnRemoverFornecedor.setText("Remover");
        mnRemoverFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRemoverFornecedorActionPerformed(evt);
            }
        });
        mnFornecedor.add(mnRemoverFornecedor);

        jMenuBar1.add(mnFornecedor);

        mnVenda.setText("Venda");

        mnCadastrarVenda.setText("Cadastrar");
        mnCadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarVendaActionPerformed(evt);
            }
        });
        mnVenda.add(mnCadastrarVenda);

        mnConsultarVenda.setText("Consultar");
        mnConsultarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnConsultarVendaActionPerformed(evt);
            }
        });
        mnVenda.add(mnConsultarVenda);

        mnAlterarVenda.setText("Alterar");
        mnAlterarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlterarVendaActionPerformed(evt);
            }
        });
        mnVenda.add(mnAlterarVenda);

        mnRemoverVenda.setText("Remover");
        mnRemoverVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRemoverVendaActionPerformed(evt);
            }
        });
        mnVenda.add(mnRemoverVenda);

        jMenuBar1.add(mnVenda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarProdutoActionPerformed
        // TODO add your handling code here:
        FormCadastrarProduto form = new FormCadastrarProduto();
        form.setVisible(true);
    }//GEN-LAST:event_mnCadastrarProdutoActionPerformed

    private void mnConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarProdutoActionPerformed
        // TODO add your handling code here:
        FormConsultarProduto form = new FormConsultarProduto();
        form.setVisible(true);
    }//GEN-LAST:event_mnConsultarProdutoActionPerformed

    private void mnAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlterarProdutoActionPerformed
        // TODO add your handling code here:
        FormAtualizarProduto form = new FormAtualizarProduto();
        form.setVisible(true);
    }//GEN-LAST:event_mnAlterarProdutoActionPerformed

    private void mnRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRemoverProdutoActionPerformed
        // TODO add your handling code here:
        FormRemoverProduto form = new FormRemoverProduto();
        form.setVisible(true);
    }//GEN-LAST:event_mnRemoverProdutoActionPerformed

    private void mnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarClienteActionPerformed
        // TODO add your handling code here:
        FormCadastrarCliente form = new FormCadastrarCliente();
        form.setVisible(true);
    }//GEN-LAST:event_mnCadastrarClienteActionPerformed

    private void mnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarClienteActionPerformed
        // TODO add your handling code here:
        FormConsultarCliente form = new FormConsultarCliente();
        form.setVisible(true);
    }//GEN-LAST:event_mnConsultarClienteActionPerformed

    private void mnAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlterarClienteActionPerformed
        // TODO add your handling code here:
        FormAtualizarCliente form = new FormAtualizarCliente();
        form.setVisible(true);
    }//GEN-LAST:event_mnAlterarClienteActionPerformed

    private void mnRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRemoverClienteActionPerformed
        // TODO add your handling code here:
        FormRemoverCliente form = new FormRemoverCliente();
        form.setVisible(true);
    }//GEN-LAST:event_mnRemoverClienteActionPerformed

    private void mnCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarFuncionarioActionPerformed
        // TODO add your handling code here:
        FormCadastrarFuncionario form = new FormCadastrarFuncionario();
        form.setVisible(true);
    }//GEN-LAST:event_mnCadastrarFuncionarioActionPerformed

    private void mnConsultarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarFuncionarioActionPerformed
        // TODO add your handling code here:
        FormConsultarFuncionario form = new FormConsultarFuncionario();
        form.setVisible(true);
    }//GEN-LAST:event_mnConsultarFuncionarioActionPerformed

    private void mnAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlterarFuncionarioActionPerformed
        // TODO add your handling code here:
        FormAtualizarFuncionario form = new FormAtualizarFuncionario();
        form.setVisible(true);
    }//GEN-LAST:event_mnAlterarFuncionarioActionPerformed

    private void mnRemoverFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRemoverFuncionarioActionPerformed
        // TODO add your handling code here:
        FormRemoverFuncionario form = new FormRemoverFuncionario();
        form.setVisible(true);
    }//GEN-LAST:event_mnRemoverFuncionarioActionPerformed

    private void mnCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarFornecedorActionPerformed
        // TODO add your handling code here:
        FormCadastrarFornecedor form = new FormCadastrarFornecedor();
        form.setVisible(true);
    }//GEN-LAST:event_mnCadastrarFornecedorActionPerformed

    private void mnConsultarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarFornecedorActionPerformed
        // TODO add your handling code here:
        FormConsultarFornecedor form = new FormConsultarFornecedor();
        form.setVisible(true);
    }//GEN-LAST:event_mnConsultarFornecedorActionPerformed

    private void mnAlterarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlterarFornecedorActionPerformed
        // TODO add your handling code here:
        FormAtualizarFornecedor form = new FormAtualizarFornecedor();
        form.setVisible(true);
    }//GEN-LAST:event_mnAlterarFornecedorActionPerformed

    private void mnRemoverFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRemoverFornecedorActionPerformed
        // TODO add your handling code here:F
        FormRemoverFornecedor form = new FormRemoverFornecedor();
        form.setVisible(true);
    }//GEN-LAST:event_mnRemoverFornecedorActionPerformed

    private void mnCadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarVendaActionPerformed
        // TODO add your handling code here:
        FormCadastrarVenda form = new FormCadastrarVenda();
        form.setVisible(true);
    }//GEN-LAST:event_mnCadastrarVendaActionPerformed

    private void mnConsultarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnConsultarVendaActionPerformed
        // TODO add your handling code here:
        FormConsultarVenda form = new FormConsultarVenda();
        form.setVisible(true);
    }//GEN-LAST:event_mnConsultarVendaActionPerformed

    private void mnAlterarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlterarVendaActionPerformed
        // TODO add your handling code here:
        FormAtualizarVenda form = new FormAtualizarVenda();
        form.setVisible(true);
    }//GEN-LAST:event_mnAlterarVendaActionPerformed

    private void mnRemoverVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRemoverVendaActionPerformed
        // TODO add your handling code here:
        FormRemoverVenda form = new FormRemoverVenda();
        form.setVisible(true);
    }//GEN-LAST:event_mnRemoverVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem mnAlterarCliente;
    private javax.swing.JMenuItem mnAlterarFornecedor;
    private javax.swing.JMenuItem mnAlterarFuncionario;
    private javax.swing.JMenuItem mnAlterarProduto;
    private javax.swing.JMenuItem mnAlterarVenda;
    private javax.swing.JMenuItem mnCadastrarCliente;
    private javax.swing.JMenuItem mnCadastrarFornecedor;
    private javax.swing.JMenuItem mnCadastrarFuncionario;
    private javax.swing.JMenuItem mnCadastrarProduto;
    private javax.swing.JMenuItem mnCadastrarVenda;
    private javax.swing.JMenu mnCliente;
    private javax.swing.JMenuItem mnConsultarCliente;
    private javax.swing.JMenuItem mnConsultarFornecedor;
    private javax.swing.JMenuItem mnConsultarFuncionario;
    private javax.swing.JMenuItem mnConsultarProduto;
    private javax.swing.JMenuItem mnConsultarVenda;
    private javax.swing.JMenu mnFornecedor;
    private javax.swing.JMenu mnFuncionario;
    private javax.swing.JMenu mnProduto;
    private javax.swing.JMenuItem mnRemoverCliente;
    private javax.swing.JMenuItem mnRemoverFornecedor;
    private javax.swing.JMenuItem mnRemoverFuncionario;
    private javax.swing.JMenuItem mnRemoverProduto;
    private javax.swing.JMenuItem mnRemoverVenda;
    private javax.swing.JMenu mnVenda;
    // End of variables declaration//GEN-END:variables
}
