package lojaEsportiva.gui;

import javax.swing.JOptionPane;
import lojaEsportiva.dados.Cliente;
import lojaEsportiva.dados.Funcionarios;
import lojaEsportiva.dados.Produto;
import lojaEsportiva.dados.Venda;
import lojaEsportiva.exceptions.ClienteNaoEncontradoException;
import lojaEsportiva.exceptions.FuncionarioNaoExistenteException;
import lojaEsportiva.exceptions.ProdutoNaoEncontradoException;
import lojaEsportiva.exceptions.VendaNaoEncontradaException;

public class FormAtualizarVenda extends javax.swing.JFrame {

    /**
     * Creates new form FormAtualizarVenda
     */
    public FormAtualizarVenda() {
        initComponents();
    }

    private boolean validaCampos() {
        if (!((txtID.getText().length() > 0) && (txtID.getText() != null))) {
            JOptionPane.showMessageDialog(null, "O campo ID deve ser informado!");
            txtID.requestFocus();
            return false;
        }
        if (!((txtIdProduto.getText().length() > 0) && (txtIdProduto.getText() != null))) {
            JOptionPane.showMessageDialog(null, "O campo ID Produto deve ser informado!");
            txtIdProduto.requestFocus();
            return false;
        }
        if (!((txtCpfCliente.getText().length() > 0) && (txtCpfCliente.getText() != null))) {
            JOptionPane.showMessageDialog(null, "O campo CPF Cliente deve ser informado!");
            txtCpfCliente.requestFocus();
            return false;
        }
        if (!((txtIdFuncionario.getText().length() > 0) && (txtIdFuncionario.getText() != null))) {
            JOptionPane.showMessageDialog(null, "O campo ID Funcionario deve ser informado!");
            txtIdFuncionario.requestFocus();
            return false;
        }
        return true;
    }
    
    private void limparCampos() {
        txtID.setText("");
        txtIdProduto.setText("");
        txtCpfCliente.setText("");
        txtIdFuncionario.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtIdProduto = new javax.swing.JTextField();
        txtCpfCliente = new javax.swing.JTextField();
        txtIdFuncionario = new javax.swing.JTextField();
        btAtualizar = new javax.swing.JButton();

        setTitle("Atualizar Venda");
        setResizable(false);

        jLabel1.setText("ID");

        jLabel2.setText("ID Produto");

        jLabel3.setText("CPF Cliente");

        jLabel4.setText("ID Funcionário");

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btAtualizar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtIdProduto))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCpfCliente))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtIdFuncionario))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIdFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btAtualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        // TODO add your handling code here:
          if (validaCampos()) {
            try{
                Produto produto = FormPrincipal.fachada.procurarProduto(txtIdProduto.getText());
                Cliente cliente = FormPrincipal.fachada.procurarCliente(txtCpfCliente.getText());
                Funcionarios funcionario = FormPrincipal.fachada.procurarFuncionario(txtIdFuncionario.getText());
                Venda venda = new Venda(produto, cliente, funcionario, txtID.getText());
                FormPrincipal.fachada.atualizarVenda(venda);
                JOptionPane.showMessageDialog(null, "Registro de venda atualizado com sucesso!");
                limparCampos();
            } catch (VendaNaoEncontradaException | ProdutoNaoEncontradoException | ClienteNaoEncontradoException | FuncionarioNaoExistenteException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
                limparCampos();
            }    
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAtualizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAtualizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAtualizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAtualizarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAtualizarVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIdFuncionario;
    private javax.swing.JTextField txtIdProduto;
    // End of variables declaration//GEN-END:variables
}
